#!/bin/sh
source lib/colors

info () {
  printf "\r\033[2K  [ ${BLUE}..${RESET} ] ${WHITE}${BOLD}$1${RESET}\n"
}

warn () {
  printf "\r\033[2K  [${YELLOW}WARN${RESET}] $1\n"
}

success () {
  printf "\r\033[2K  [ ${GREEN}OK${RESET} ] $1\n"
}

fail () {
  printf "\r\033[2K  [${RED}FAIL${RESET}] $1\n"
  echo ''
  exit
}

