#!/bin/sh

set -e

source $(dirname "$0")/util.sh
source $(dirname "$0")/spinner.sh

SERVER=$1

title "Brew Setup"

# Ask for the administrator password upfront
# sudo -v

# Make sure we’re using the latest Homebrew
start_spinner "Updating and upgrading brew…"
brew update >/dev/null 2>&1
brew upgrade >/dev/null 2>&1
stop_spinner
success "Brew updated and upgraded"

# Taps
start_spinner "Tapping…"
# brew tap eddieantonio/eddieantonio
# brew tap osx-cross/avr
# brew tap sudar/arduino-mk
# brew tap mongodb/brew
brew tap leoafarias/fvm
stop_spinner
success "Tapped"

FORMULAS=(
  # Updated/nicer/faster tools
  coreutils # GNU core utilities (those that come with OS X are outdated)
  findutils # GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

  wget # Wget with iri
  ncdu # Nicer du
  gnupg
  less # Newer less
  ack
  the_silver_searcher
  fzf
  ripgrep # Faster grepping
  fd # Decent file searcher

  # Useful tools
  jq # JSON parser

  # Terminal helpers and tools
  zoxide # aka: z
  zsh-autosuggestions
  zsh-syntax-highlighting

  # Git
  git
  git-lfs
  lazygit
  git-delta
  diff-so-fancy

  # Mah IDE
  tmux
  neovim
  ranger
  todo-txt

  # Certificate tools
  openssl
  mkcert
  gpg

  # Languages
  node
  haskell-stack
  python3
  rustup
  fvm
  java
  dotnet
  golang

  # Other language frameworks, libs and bits
  platformio
  esphome

  # Compilers
  make
  cmake
  ccls
  mono

  # Dev helpers
  # watchman
  # fswatch
  # awscli
  # azure-cli

  # Gifiy
  # ffmpeg
  # gifsicle
  # imagemagick
)

CASKS=(
  kitty

  # Gifify
  # xquartz

  # Dev Tools
  # react-native-debugger
  # imageoptim

  # Other
  #dropbox
  appcleaner

  docker

  # sim-daltonism # Color blindness simulator

  # slack

  figma

  bricklink-studio
  kicad

  dosbox
)

CASKS_SERVER=(
  kitty

  nginx
  sabnzbd
  sonarr
  radarr
  transmission
  plex-media-server

  virtualbox
)

# TODO: To Save
# Fonts

# Not available or still figuring out:
# Xcode

INSTALLED=$(brew list)

formula_exists() {
  if $(echo $INSTALLED | grep $1 > /dev/null); then
    return 0
  fi

  return 1
}

title "Install brews"

for index in ${!FORMULAS[*]}
do
  if ! formula_exists ${FORMULAS[$index]}; then
    start_spinner "Installing $(tput bold)${FORMULAS[$index]}$(tput sgr0)…"
    brew install ${FORMULAS[$index]} >/dev/null 2>&1
    stop_spinner
    success "$(tput bold)${FORMULAS[$index]}$(tput sgr0) installed"
  else
    skip "$(tput bold)${FORMULAS[$index]}$(tput sgr0)$(tput setaf 8) already installed, skipping"
  fi
done

if [ "$SERVER" == "server" ];
then
  CASK_LIST=("${CASKS_SERVER[@]}")
else
  CASK_LIST=("${CASKS[@]}")
fi

title "Install brew casks"

for index in ${!CASK_LIST[*]}
do
  if ! formula_exists ${CASK_LIST[$index]}; then
    start_spinner "Installing $(tput bold)${CASK_LIST[$index]}$(tput sgr0)…"
    brew install --cask ${CASK_LIST[$index]} >/dev/null 2>&1
    success "$(tput bold)${CASK_LIST[$index]}$(tput sgr0) installed"
  else
    skip "$(tput bold)${CASK_LIST[$index]}$(tput sgr0)$(tput setaf 8) already installed, skipping"
  fi
done

title "Clean up"

start_spinner "Brews installed, cleaning up…"
brew cleanup >/dev/null 2>&1
stop_spinner
success "Brew cleaned up"
