#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# GNU core utilities (those that come with OS X are outdated)
brew install coreutils

# GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Bash 4
brew install bash

# wget with IRI support
brew install wget --enable-iri

# more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# rbenv
brew install rbenv ruby-build

# everything else
brew install ack
brew install git bash-completion
brew install node
brew install rename
brew install tree

# Stuff needed for gifify
brew install ffmpeg
brew tap phinze/homebrew-cask
brew install brew-cask
brew cask install x-quartz
open /usr/local/Cellar/x-quartz/2.7.4/XQuartz.pkg
# click through the stuff
brew install gifsicle
brew install imagemagick

# Remove outdated versions from the cellar
brew cleanup
