#!/bin/sh

set -e

source ./lib/output.sh

tit "Brew Setup"

# Ask for the administrator password upfront
sudo -v

# Make sure we’re using the latest Homebrew
info "Update and upgrade brew"
brew update && brew upgrade

# Taps
info "Tapping"
brew tap eddieantonio/eddieantonio
brew tap osx-cross/avr
brew tap sudar/arduino-mk

FORMULAS=(
  # GNU core utilities (those that come with OS X are outdated)
  coreutils

  # GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
  findutils

  # Shells
  bash
  zsh

  # Wget with iri
  "wget --enable-iri"

  # Git
  git
  tig

  # Mah IDE
  # Uninstall first? Upgrade drops the override-system-vim
  "macvim --with-override-system-vim"

  # Useful tools
  trash
  ack
  the_silver_searcher
  rename
  todo-txt
  httpie
  fzf
  z
  diff-so-fancy
  yarn
  awscli
  watchman
  fswatch
  ranger
  imgcat
  jq # JSON parser
  fontforge # For custom font icon patching

  # Languages
  node
  python
  python3

  # Ruby stuff
  rbenv
  ruby-build

  # Compilers
  make
  cmake
  mono

  # Gifiy
  ffmpeg
  gifsicle
  imagemagick

  # Kivy
  pkg-config
  sdl2
  sdl2_image
  sdl2_ttf
  sdl2_mixer
  gstreamer

  # Arduino
  avr-libc
  avrdude
  arduino-mk
  platformio
)

CASKS=(
  iterm2

  # Quicklook Add-ins
  qlcolorcode
  qlstephen
  qlmarkdown
  quicklook-json
  qlprettypatch
  quicklook-csv
  betterzipql
  qlimagesize

  # Gifify
  xquartz

  # Dev Tools
  react-native-debugger
  android-studio
  intel-haxm
  java
  fastlane
  imageoptim
  google-chrome
  firefoxdeveloperedition

  # Misc
  caprine   # Facebook Messenger

  # Other
  dropbox
  appcleaner

  docker

  sip # Color select/organise

  slack

  sketch
  figma
  principle
  balsamiq-mockups
  zeplin

  dosbox
  calibre
  disk-inventory-x
  the-unarchiver # RAR
)

# TODO: To Save
# Fonts

# Not available or still figuring out:
# Syncplicity
# OpenVPN
# MindNode
# Xcode
# Day One?
# Sim Daltonism

formula_exists() {
  if $(brew list | grep $1 > /dev/null); then
    return 0
  fi

  return 1
}

cask_exists() {
  if $(brew cask list | grep $1 > /dev/null); then
    return 0
  fi

  return 1
}


for index in ${!FORMULAS[*]}
do
  if ! formula_exists ${FORMULAS[$index]}; then
    info "${FORMULAS[$index]} not installed, installing..."
    brew install ${FORMULAS[$index]}
  else
    success "${FORMULAS[$index]} already installed, skipping"
  fi
done

for index in ${!CASKS[*]}
do
  if ! cask_exists ${CASKS[$index]}; then
    info "${CASKS[$index]} not installed, installing..."
    brew cask install ${CASKS[$index]}
  else
    success "${CASKS[$index]} already installed, skipping"
  fi
done

# more recent versions of some OS X tools
brew install homebrew/dupes/grep

# TODO: Needed?
# open /usr/local/Cellar/x-quartz/2.7.4/XQuartz.pkg

# Remove outdated versions from the cellar
brew cleanup
