SGR0=$(tput sgr0)
BOLD=$(tput bold)
ITALIC=$'\e[3m'
BOLD_ITALIC=$'\e[1;3m'
UNDERLINE=$(tput smul)
UNDERCURL=$'\e[4:3m'

FG_BLACK=$(tput setaf 0)
FG_RED=$(tput setaf 1)
FG_GREEN=$(tput setaf 2)
FG_YELLOW=$(tput setaf 3)
FG_BLUE=$(tput setaf 4)
FG_MAGENTA=$(tput setaf 5)
FG_CYAN=$(tput setaf 6)
FG_WHITE=$(tput setaf 7)

FG_BRIGHT_BLACK=$(tput setaf 8)
FG_BRIGHT_RED=$(tput setaf 9)
FG_BRIGHT_GREEN=$(tput setaf 10)
FG_BRIGHT_YELLOW=$(tput setaf 11)
FG_BRIGHT_BLUE=$(tput setaf 12)
FG_BRIGHT_MAGENTA=$(tput setaf 13)
FG_BRIGHT_CYAN=$(tput setaf 14)
FG_BRIGHT_WHITE=$(tput setaf 15)

BG_BLACK=$(tput setab 0)
BG_RED=$(tput setab 1)
BG_GREEN=$(tput setab 2)
BG_YELLOW=$(tput setab 3)
BG_BLUE=$(tput setab 4)
BG_MAGENTA=$(tput setab 5)
BG_CYAN=$(tput setab 6)
BG_WHITE=$(tput setab 7)

BG_BRIGHT_BLACK=$(tput setab 8)
BG_BRIGHT_RED=$(tput setab 9)
BG_BRIGHT_GREEN=$(tput setab 10)
BG_BRIGHT_YELLOW=$(tput setab 11)
BG_BRIGHT_BLUE=$(tput setab 12)
BG_BRIGHT_MAGENTA=$(tput setab 13)
BG_BRIGHT_CYAN=$(tput setab 14)
BG_BRIGHT_WHITE=$(tput setab 15)
