#!/bin/sh

npm install -g \
  instant-markdown-d
#   create-react-app \
#   react-native-cli \
#   import-js \
#   janeway

# NVM
# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
