#!/bin/sh

npm install -g \
  create-react-app \
  react-native-cli \
  import-js \
  instant-markdown-d \
  janeway

# NVM
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
