#!/bin/bash

# Web dev essentials
npm install -g yo grunt-cli bower

# Markdown previewer
npm install -g greadme

# Some Yeoman generators
npm install -g generator-angular
npm install -g generator-angular-fullstack
npm install -g generator-jekyllrb
npm install -g generator-webapp
