#!/usr/bin/env bash

source $(dirname "$0")/util.sh
source $(dirname "$0")/spinner.sh

title "Rust Setup"

start_spinner "Setting up Rust…"
rustup default stable >/dev/null 2>&1
stop_spinner
success "Rust Set Up"

APPS=(
  todotxt-tui
)

title "Install Rust Apps"

for index in ${!APPS[*]}
do
  which ${APPS[$index]} >/dev/null

  if [ ! $? -eq 0 ]; then
    start_spinner "Installing $(tput bold)${APPS[$index]}$(tput sgr0)…"
    cargo install ${APPS[$index]} >/dev/null 2>&1
    stop_spinner
    success "$(tput bold)${APPS[$index]}$(tput sgr0) installed"
  else
    skip "$(tput bold)${APPS[$index]}$(tput sgr0)$(tput setaf 8) already installed, skipping"
  fi
done
